spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fast-time
    username: root
    password: 1234
  jpa:
    hibernate:
      show-sql: true
      jdbc:
        time_zone: Asia/Seoul
