spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fasttime
    username: root
    password: 1234
  jpa:
    hibernate:
      show-sql: true
      jdbc:
        time_zone: Asia/Seoul
  mail:
    username: fasttime123
    password: dnwnrlfls123
